dsn: root:wui11413@tcp(127.0.0.1:3306)/chilian_user?charset=utf8mb4&parseTime=True&loc=Local
dir: ./model
tables:
prefix:
style: snake
template:

# 关联关系配置
relations:
  user: # 用户表关联关系
    - target: user_login_log
      type: has_many
      foreign_key: user_id
      references: id
